### ISSUE TITLE
ERROR: Missing results

### ISSUE THREAD

**Issue by alexsanyum** [ncbi/elastic-blast#14]
Hello there, 

I am trying to use elastic-blast on a amazon ec2, and s3 bucket. 
I have a large EC2 instance, I also created an user with the IAM policy  that it is specified in this link:
https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/iam-policy.html

I already have my FASTA files in the bucket, and created the configuration file as indicated in the website.

[cloud-provider]
aws-region = us-east-1

[cluster]
num-nodes = 8
labels = owner=YOURNAME

[blast]
program = blastn
db = nt
queries = s3://MY_BUCKET/samples/sample1.fasta
results = s3://MY_BUCKET/results/BDQA1
options = -task  dc-megablast -outfmt "6 qseqid sseqid staxids sskingdoms pident mismatch"  -max_target_seqs 20

However, when I try to run, I got ERROR: Missing results.

Checking the log file, I got this messages:
2023-04-19T15:12:33.643048Z INFO: ElasticBLAST submit 1.0.0
2023-04-19T15:12:33.643478Z ERROR: Missing results
2023-04-19T15:12:33.643698Z DEBUG: Clean up with stack 

I dont know how to solve this problem. I think maybe is because the fasta files I have. I created them in python, with my own code from files that were generated from stacks program.
The fasta files I have seems like this:
~~~
>120623 Sample:3.0
AAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
>79314 Sample:3.0
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAGGGGGGGGGC
~~~
Sequences are just in one line, not spitted in several lines every 100 bp like sequences I download from NCBI. 

I really appreciate your help,
Alex

**Comment by boratyng** [comment]
Hi @alexsanyum,

  Thank you for trying out elastic-blast and we are sorry that you ran into a problem. The message `ERROR: Missing results.` indicates that the `results` parameter is missing in your config file. Could you try submitting the elastic-blast search with the config file that you posted again? I see the results parameter:
```
results = s3://MY_BUCKET/results/BDQA1
```
but it is possible that some non-ASCII character caused problems. Also, you need to correct your S3 bucket name. Upper case letters are not allowed in S3 bucket names and the names `MY_BUCKET` will result in another error message. Please, let us know if you need more help.

**Comment by alexsanyum** [comment]
There is no non-ASCII character in the bucket name. The one that I use is called oreos3. I will try to run it again, but what information do you need in order to help me (I don't have that very clear)

**Comment by alexsanyum** [comment]
Hello there, 

Thanks for your response. I have some new problems with the permissions, but I think I solved them. 

First, when I try again says I miss DescribeInstanceTypeOfferings permission, so I created a new policy and the problem was solved.
But I got the same error

This is my configuration file:
~~~
[cloud-provider]
aws-region =us-east-1

[cluster]
num-nodes = 8
labels = owner=YOURNAME

[blast]
program = blastn
db = nt
queries = s3://oreos3/meta_data/fasta_files/Ab_365_CGAAT-CGATGT.fasta
results = s3://oreos3/meta_data/results
options = -task dc-megablast -evalue 0.01 -outfmt "6 qseqid sseqid staxids sskingdoms pident mismatch" -max_target_seqs 20 
~~~

And the log file:
~~~
2023-04-20T15:03:58.078323Z INFO: ElasticBLAST submit 1.0.0
2023-04-20T15:03:58.078636Z ERROR: Missing results
2023-04-20T15:03:58.078748Z DEBUG: Clean up with stack 
2023-04-20T15:10:02.000419Z INFO: ElasticBLAST submit 1.0.0
2023-04-20T15:10:02.000788Z ERROR: Missing results
2023-04-20T15:10:02.000902Z DEBUG: Clean up with stack 
~~~

**Comment by boratyng** [comment]
I am glad to hear that you solved the permissions problem. DescribeInstanceTypeOfferings was indeed missing in our policy page. We are going to update our documentation.

Unfortunately I am not able to reproduce your problem with your elastic-blast config file. Please, provide the information listed in the page: https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/support.html. Thanks!

**Comment by boratyng** [comment]
@alexsanyum, can you also attach (not paste) the elastic-blast config file that you are using? Thanks!

**Comment by alexsanyum** [comment]
Thanks for the help,

I already send the documentation to the email that it is provided. 

You can mark this Issue as solved if you want. I'll keep trying to fix this problem I have via mail.
