### ISSUE TITLE
ERROR: "elasticblast-my-user-name" is not a valid GKE cluster name. 

### ISSUE THREAD

**Issue by elasekness** [ncbi/elastic-blast#16]
When I submit my elastic-blast job, I receive the following message:
ERROR: "elasticblast-my-username" is not a valid GKE cluster name.
The string must be less than 40 characters and can only contain lowercase letters, digits, and dashes.

I'm not sure how to work around this problem as my username in GCP is my first and last name separated by underscores,
which appears to be an illegal character.

**Comment by christiam** [comment]
@elasekness , have you tried setting the cluster name configuration setting: https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/configuration.html#cluster-name ?

**Comment by christiam** [comment]
I haven't heard anything regarding the suggestion above, so I'm closing this issue. Please feel free to reopen if the suggestion above doesn't work for you.
