### ISSUE TITLE
QUESTION: Is it possible to run elastic blast locally but with database in AWS S3?

### ISSUE THREAD

**Issue by shreyas-a-s** [ncbi/elastic-blast#17]
Hi there!

I have a server that has blast deployed and the blast databases are also in the server. But due to the ever increasing number of blast databases I was thinking of a way to move them to AWS S3 and access it from there during blast runs. I tried it with normal blast and it was not accepting any input data from the cloud. When it comes to elastic-blast, I was able to configure and run it but everytime it runs on a newly created EC2 instance which is incurring more cost. Is it possible to run blasts locally but using database stored in S3? Any kind of input on this scenario is appreciated.

Thanks in advance.

**Comment by christiam** [comment]
> Is it possible to run blasts locally but using database stored in S3?

I'm sorry, but this is not supported.

**Comment by shreyas-a-s** [comment]
Okay. That's fine. Btw is it possible to set the ec2 that is used for the blast run to a lowered powered one? Maybe by using the .ini file.

**Comment by christiam** [comment]
Yes, you can set the instance type used via the `machine-type` configuration setting: https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/configuration.html#elb-machine-type

**Comment by shreyas-a-s** [comment]
Wow! Somehow I totally missed that part of the documentation. Thanks for pointing me in the right direction.

I think I'll go forward with elastic-blast and configure instance type based on the size of my blast databases. Because currently, storage space is my main constraint due to limited server storage size and the cost of few minutes of ec2 instance time thereby is less of an issue.

Thanks again.
