### ISSUE TITLE
igblast

### ISSUE THREAD

**Issue by mayla-abrahim** [ncbi/elastic-blast#5]
Congratulations, the project is very good!
I would like to know if it is possible to use igblatn in ElasticBLAST?
And if it is not possible, is there a plan to implement igblast in ElasticBLAST?

**Comment by tom6931** [comment]
Hi, thank you for your kudos.
Currently, we do not have plans to support IgBLAST in ElasticBLAST, but it is an interesting idea.  First, we need to finish up our alpha release and then consider next steps.

**Comment by mayla-abrahim** [comment]
Thank you so much! I really liked the ElasticBLAST!
Best regards.
Mayla Abrahim
