### ISSUE TITLE
No results in output bucket 

### ISSUE THREAD

**Issue by sean-bam** [ncbi/elastic-blast#8]
I am using `elastic-blast v. 0.2.3` on a google cloud VM. When I run the tutorial to submit queries from the BDQA WGS project versus refseq_protein, I do not get the expected `*.out.gz` files. 
The output bucket contains `BDQA/metadata/` folder, so that seems to be populating just fine.
If run `elastic-blast status --cfg BDQA.ini`, I get the following:
```
Pending 0
Running 0
Succeeded 0
Failed 0
```
Any ideas why the search doesn't seem to be completing?

**Comment by christiam** [comment]
Hi @sean-bam , 
      I don't have enough information to diagnose the problem. Do you consistently get the output shown above for the ``elastic-blast status`` command? How long has it been since you ran ``elastic-blast submit ...`` ? Also, could you please provide us with the information listed in the following page? https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/support.html
Thanks, regards,

Christiam

**Comment by christiam** [comment]
Hi @sean-bam , 
       Did your ElasticBLAST search complete?
Thanks, regards,

Christiam

**Comment by sean-bam** [comment]
>Do I understand correctly that you can [get BLAST output from the results bucket](https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/quickstart-gcp.html#download-results)?

Yes. 

>what exactly is the output of elastic-blast status that indicates that the job did not finish successfully? 

As you mentioned, if I run `elastic-blast status` immediately after `elastic-blast submit`, the output is 
```
Pending 0
Running 0
Succeeded 0
Failed 0
```
This led me to believe that the program didn't submit/run/complete. However, now that I know to wait a short period of time to check the status, I can see that `elastic-blast` is doing its job just fine, and that the problem was with me being impatient :)  Sorry for the trouble!

**Comment by sbenler** [comment]
Will do, thanks for fixing this small issue!
