### ISSUE TITLE
Tasks always on "Pending" and the last line in the log file shows “DEBUG: Clean up with stack”

### ISSUE THREAD

**Issue by NickShanyt** [ncbi/elastic-blast#9]
Hey, to save quick startup time on AWS, I uploaded the short sequence into the AWS bucket as input; then I modified the " num-nodes = 1" configuration file because I was using AWS's free package. But the submitted task was in Pending state, and I couldn't find any obvious errors in the logs.

Maybe I can e-mail you my files.
————————————————————BDQA.ini———————————————————————— 
[cloud-provider]
aws-region = us-east-1

[cluster]
num-nodes = 1
labels = owner=liuxue

[blast]
program = blastp
db = refseq_protein
queries = s3://elasticblast-liuxue/input/AS-31-pro.txt
results = s3://elasticblast-liuxue/results/BDQA
options = -task blastp-fast -evalue 0.01 -outfmt "7 std sskingdoms ssciname"

————————————————————elastic-blast.log————————————————————
……

2022-02-24T02:35:28.455320Z DEBUG: NumJobs 2 Pending 2 Running 0 Succeeded 0 Failed 0
2022-02-24T02:35:28.455443Z DEBUG: Pending 2
Running 0
Succeeded 0
Failed 0
2022-02-24T02:35:28.460436Z DEBUG: Clean up with stack

**Comment by christiam** [comment]
Hi @NickShanyt ,
          It is expected for there to be pending jobs at the start of any ElasticBLAST search, this happens as compute resources are being allocated and jobs are scheduled to run. Once they start running, the output of `elastic-blast status` should reflect that. Have you found that not to be the case? If so, could you please provide us with the information on the [support page](https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/support.html)? On the other hand, you can safely ignore any entries in the logfile with the keyword `DEBUG`.
Thanks in advance, regards,

Christiam

**Comment by christiam** [comment]
Hi @NickShanyt , I just wanted to let you know that [the latest ElasticBLAST release (version 0.2.4) ](https://github.com/ncbi/elastic-blast/releases/tag/0.2.4) fixes a problem that led to the output from `elastic-blast status` showing 0 for all job states (when immediately run after `elastic-blast submit`). 

Please let us know if you run into any problems and/or have any feedback with this latest release. Thanks!
